# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('rodzaj', models.CharField(choices=[('miasto', 'miasto'), ('wieś', 'wieś'), ('statki', 'statki'), ('zagranica', 'zagranica')], max_length=100)),
                ('liczba_mieszkancow', models.IntegerField()),
                ('liczba_uprawnionych', models.IntegerField()),
                ('liczba_wydanych_kart', models.IntegerField()),
                ('liczba_glosow_oddanych', models.IntegerField()),
                ('liczba_glosow_kandydat_a', models.IntegerField()),
                ('liczba_glosow_kandydat_b', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gmina',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Wojewodztwo'),
        ),
    ]
