# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wynik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gmina',
            options={'verbose_name_plural': 'gminy'},
        ),
        migrations.AlterModelOptions(
            name='kandydat',
            options={'verbose_name_plural': 'kandydaci'},
        ),
        migrations.AlterModelOptions(
            name='wojewodztwo',
            options={'verbose_name_plural': 'województwa'},
        ),
        migrations.AddField(
            model_name='wynik',
            name='gmina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Gmina'),
        ),
        migrations.AddField(
            model_name='wynik',
            name='kandydat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki.Kandydat'),
        ),
        migrations.AlterUniqueTogether(
            name='wynik',
            unique_together=set([('kandydat', 'gmina')]),
        ),
    ]
