# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0002_auto_20160408_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wynik',
            options={'verbose_name_plural': 'wyniki'},
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='liczba_glosow_kandydat_a',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='liczba_glosow_kandydat_b',
        ),
    ]
