# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyniki', '0004_gmina_data_modyfikacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='uzytkownik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
